# Generated by Django 5.2.1 on 2025-09-05 10:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pledge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Pledge amount per frequency period', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('frequency', models.CharField(choices=[('one-time', 'One Time'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')], help_text='How often the pledge is made', max_length=20)),
                ('start_date', models.DateField(default=django.utils.timezone.now, help_text='When the pledge starts')),
                ('end_date', models.DateField(blank=True, help_text='When the pledge ends (optional for ongoing pledges)', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('paused', 'Paused')], default='active', help_text='Current status of the pledge', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the pledge')),
                ('total_pledged', models.DecimalField(decimal_places=2, default=0, help_text='Total amount pledged over the commitment period', max_digits=12)),
                ('total_received', models.DecimalField(decimal_places=2, default=0, help_text='Total amount actually received', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(help_text='Member making the pledge', on_delete=django.db.models.deletion.CASCADE, related_name='pledges', to='members.member')),
            ],
            options={
                'verbose_name': 'Pledge',
                'verbose_name_plural': 'Pledges',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PledgePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_date', models.DateField(default=django.utils.timezone.now, help_text='Date when payment was received')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('check', 'Check'), ('card', 'Credit/Debit Card'), ('bank_transfer', 'Bank Transfer'), ('online', 'Online Payment'), ('mobile', 'Mobile Payment'), ('other', 'Other')], default='cash', max_length=20)),
                ('reference_number', models.CharField(blank=True, help_text='Check number, transaction ID, etc.', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the payment')),
                ('recorded_by', models.CharField(blank=True, help_text='Who recorded this payment', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='pledges.pledge')),
            ],
            options={
                'verbose_name': 'Pledge Payment',
                'verbose_name_plural': 'Pledge Payments',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PledgeReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reminder_type', models.CharField(choices=[('upcoming', 'Upcoming Payment'), ('overdue', 'Overdue Payment'), ('thank_you', 'Thank You'), ('completion', 'Pledge Completion')], max_length=20)),
                ('reminder_method', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('phone', 'Phone Call'), ('mail', 'Physical Mail')], max_length=20)),
                ('sent_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.TextField(help_text='Content of the reminder sent')),
                ('sent_by', models.CharField(help_text='Who sent the reminder', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='pledges.pledge')),
            ],
            options={
                'verbose_name': 'Pledge Reminder',
                'verbose_name_plural': 'Pledge Reminders',
                'ordering': ['-sent_date'],
            },
        ),
        migrations.AddIndex(
            model_name='pledge',
            index=models.Index(fields=['member', 'status'], name='pledges_ple_member__618bac_idx'),
        ),
        migrations.AddIndex(
            model_name='pledge',
            index=models.Index(fields=['frequency', 'status'], name='pledges_ple_frequen_e3e32b_idx'),
        ),
        migrations.AddIndex(
            model_name='pledge',
            index=models.Index(fields=['start_date', 'end_date'], name='pledges_ple_start_d_09ebe4_idx'),
        ),
        migrations.AddIndex(
            model_name='pledge',
            index=models.Index(fields=['created_at'], name='pledges_ple_created_deafa1_idx'),
        ),
        migrations.AddIndex(
            model_name='pledge',
            index=models.Index(fields=['status', 'start_date'], name='pledges_ple_status_5b6121_idx'),
        ),
        migrations.AddIndex(
            model_name='pledgepayment',
            index=models.Index(fields=['pledge', 'payment_date'], name='pledges_ple_pledge__ff0d8e_idx'),
        ),
        migrations.AddIndex(
            model_name='pledgepayment',
            index=models.Index(fields=['payment_date'], name='pledges_ple_payment_d82e8a_idx'),
        ),
        migrations.AddIndex(
            model_name='pledgepayment',
            index=models.Index(fields=['payment_method'], name='pledges_ple_payment_0c941b_idx'),
        ),
        migrations.AddIndex(
            model_name='pledgepayment',
            index=models.Index(fields=['created_at'], name='pledges_ple_created_16cd12_idx'),
        ),
    ]
