# Generated by Django 5.2.1 on 2025-09-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginattempt',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
