# Generated by Django 5.2.1 on 2025-12-20 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_loginattempt_success'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Administrator'), ('admin', 'Administrator'), ('staff', 'Staff Member'), ('viewer', 'Viewer'), ('readonly', 'Read Only User')], db_index=True, default='readonly', help_text="User's role determining access permissions", max_length=20),
        ),
    ]
