# Generated by Django 5.2.1 on 2025-09-12 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('groups', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='target_groups',
            field=models.ManyToManyField(blank=True, help_text='Specific groups this event is targeted to', to='groups.group'),
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Event category for organization', null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.eventcategory'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to='members.member'),
        ),
        migrations.AddField(
            model_name='eventreminder',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='events.event'),
        ),
        migrations.AddField(
            model_name='eventvolunteer',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteers', to='events.event'),
        ),
        migrations.AddField(
            model_name='eventvolunteer',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_assignments', to='members.member'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_datetime'], name='events_even_start_d_b72861_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status'], name='events_even_status_5709b6_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_type'], name='events_even_event_t_a87b5c_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_public'], name='events_even_is_publ_e2e10e_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['created_at'], name='events_even_created_52c227_idx'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['status'], name='events_even_status_bdf692_idx'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['registration_date'], name='events_even_registr_83a89a_idx'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['payment_status'], name='events_even_payment_6d05c3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventregistration',
            unique_together={('event', 'member')},
        ),
        migrations.AddIndex(
            model_name='eventreminder',
            index=models.Index(fields=['send_at'], name='events_even_send_at_1b8ed6_idx'),
        ),
        migrations.AddIndex(
            model_name='eventreminder',
            index=models.Index(fields=['sent'], name='events_even_sent_50173f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventvolunteer',
            unique_together={('event', 'member', 'role')},
        ),
    ]
