# Generated by Django 5.2.1 on 2025-10-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_eventregistration_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='external_registration_url',
            field=models.URLField(blank=True, help_text='External registration link (if using third-party system)', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL to event poster or promotional image', null=True),
        ),
    ]
