# docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: churchconnect
      POSTGRES_USER: churchadmin
      POSTGRES_PASSWORD: churchpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    environment:
      - DB_NAME=churchconnect
      - DB_USER=churchadmin
      - DB_PASSWORD=churchpass
      - DB_HOST=db
      - DB_PORT=5432
      - SECRET_KEY=your-secret-key-here
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=http://backend:8000/api
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data: