# Generated by Django 5.2.1 on 2025-08-26 17:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('family_name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, help_text='Family address', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the family', null=True)),
            ],
            options={
                'verbose_name': 'Family',
                'verbose_name_plural': 'Families',
                'ordering': ['family_name'],
            },
        ),
        migrations.CreateModel(
            name='FamilyRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(choices=[('head', 'Head of Household'), ('spouse', 'Spouse'), ('child', 'Child'), ('dependent', 'Dependent'), ('other', 'Other')], default='other', help_text='Type of relationship to the family', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this relationship', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Family Relationship',
                'verbose_name_plural': 'Family Relationships',
                'ordering': ['relationship_type', 'created_at'],
            },
        ),
    ]
