# Generated by Django 5.2.1 on 2025-08-22 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='primary_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_families', to='members.member'),
        ),
        migrations.AddField(
            model_name='familyrelationship',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_relationships', to='families.family'),
        ),
        migrations.AddField(
            model_name='familyrelationship',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='family_relationship', to='members.member'),
        ),
        migrations.AlterUniqueTogether(
            name='familyrelationship',
            unique_together={('family', 'member')},
        ),
    ]
