# Generated by Django 5.2.1 on 2025-08-27 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='primary_contact',
            field=models.ForeignKey(blank=True, help_text='Primary contact for this family', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_families', to='members.member'),
        ),
        migrations.AddField(
            model_name='familyrelationship',
            name='family',
            field=models.ForeignKey(help_text='The family this relationship belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='family_relationships', to='families.family'),
        ),
        migrations.AddField(
            model_name='familyrelationship',
            name='member',
            field=models.OneToOneField(help_text='The member in this relationship', on_delete=django.db.models.deletion.CASCADE, related_name='family_relationship', to='members.member'),
        ),
        migrations.AddIndex(
            model_name='family',
            index=models.Index(fields=['family_name'], name='families_fa_family__22c8a2_idx'),
        ),
        migrations.AddIndex(
            model_name='family',
            index=models.Index(fields=['created_at'], name='families_fa_created_c4a26a_idx'),
        ),
        migrations.AddIndex(
            model_name='family',
            index=models.Index(fields=['primary_contact'], name='families_fa_primary_668b4b_idx'),
        ),
        migrations.AddIndex(
            model_name='familyrelationship',
            index=models.Index(fields=['family', 'relationship_type'], name='families_fa_family__487bd0_idx'),
        ),
        migrations.AddIndex(
            model_name='familyrelationship',
            index=models.Index(fields=['member'], name='families_fa_member__19bf4f_idx'),
        ),
        migrations.AddIndex(
            model_name='familyrelationship',
            index=models.Index(fields=['relationship_type'], name='families_fa_relatio_ccff8a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='familyrelationship',
            unique_together={('family', 'member')},
        ),
    ]
