# Generated by Django 5.2.1 on 2025-10-03 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0002_initial'),
        ('members', '0006_alter_member_alternate_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyrelationship',
            name='member',
            field=models.ForeignKey(help_text='The member in this relationship', on_delete=django.db.models.deletion.CASCADE, related_name='family_relationships', to='members.member'),
        ),
    ]
