# Generated by Django 5.2.1 on 2025-09-24 05:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_member_gender_alter_member_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='registration_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
