# Generated by Django 5.2.1 on 2025-09-27 08:51

import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0002_initial'),
        ('members', '0004_alter_member_registration_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bulkimporterror',
            options={'ordering': ['row_number'], 'verbose_name': 'Bulk Import Error', 'verbose_name_plural': 'Bulk Import Errors'},
        ),
        migrations.AlterModelOptions(
            name='bulkimportlog',
            options={'ordering': ['-started_at'], 'verbose_name': 'Bulk Import Log', 'verbose_name_plural': 'Bulk Import Logs'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['-registration_date'], 'verbose_name': 'Member', 'verbose_name_plural': 'Members'},
        ),
        migrations.AlterModelOptions(
            name='membernote',
            options={'ordering': ['-created_at'], 'verbose_name': 'Member Note', 'verbose_name_plural': 'Member Notes'},
        ),
        migrations.AlterModelOptions(
            name='membertag',
            options={'ordering': ['name'], 'verbose_name': 'Member Tag', 'verbose_name_plural': 'Member Tags'},
        ),
        migrations.AlterModelOptions(
            name='membertagassignment',
            options={'ordering': ['-assigned_at'], 'verbose_name': 'Member Tag Assignment', 'verbose_name_plural': 'Member Tag Assignments'},
        ),
        migrations.AddField(
            model_name='bulkimportlog',
            name='import_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='bulkimportlog',
            name='skipped_rows',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='employer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='marketing_consent',
            field=models.BooleanField(default=False, help_text='Consent to receive marketing communications'),
        ),
        migrations.AddField(
            model_name='member',
            name='membership_type',
            field=models.CharField(choices=[('regular', 'Regular Member'), ('associate', 'Associate Member'), ('youth', 'Youth Member'), ('senior', 'Senior Member'), ('visitor', 'Visitor'), ('honorary', 'Honorary Member')], default='regular', max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='membernote',
            name='is_confidential',
            field=models.BooleanField(default=False, help_text='Confidential notes require special permissions to view'),
        ),
        migrations.AddField(
            model_name='membernote',
            name='note_type',
            field=models.CharField(choices=[('general', 'General Note'), ('pastoral', 'Pastoral Care'), ('administrative', 'Administrative'), ('prayer_request', 'Prayer Request'), ('follow_up', 'Follow Up Required'), ('medical', 'Medical Information'), ('emergency', 'Emergency Contact')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='membernote',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='membertag',
            name='is_system_tag',
            field=models.BooleanField(default=False, help_text='System tags cannot be deleted by users'),
        ),
        migrations.AlterField(
            model_name='bulkimporterror',
            name='field_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bulkimporterror',
            name='row_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='bulkimportlog',
            name='error_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bulkimportlog',
            name='failed_rows',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bulkimportlog',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bulkimportlog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('completed_with_errors', 'Completed with Errors'), ('cancelled', 'Cancelled')], default='pending', max_length=25),
        ),
        migrations.AlterField(
            model_name='bulkimportlog',
            name='successful_rows',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bulkimportlog',
            name='total_rows',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='member',
            name='accessibility_needs',
            field=models.TextField(blank=True, help_text='Any accessibility requirements or special needs', null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.TextField(blank=True, help_text='Full address', null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='alternate_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Alternative phone number', max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='member',
            name='communication_opt_in',
            field=models.BooleanField(default=True, help_text='Consent to receive communications'),
        ),
        migrations.AlterField(
            model_name='member',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Date of birth (YYYY-MM-DD)', null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(help_text='Primary email address', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='emergency_contact_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='member',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_members', to='families.family'),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(help_text="Member's first name", max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='import_batch_id',
            field=models.UUIDField(blank=True, help_text='Batch ID if imported via bulk import', null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='import_row_number',
            field=models.IntegerField(blank=True, help_text='Row number from import file', null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='import_validation_overridden',
            field=models.BooleanField(default=False, help_text='Whether validation was overridden during import'),
        ),
        migrations.AlterField(
            model_name='member',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Internal notes not visible to the member', null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the member is currently active'),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_contact_date',
            field=models.DateTimeField(blank=True, help_text='Date of last contact with this member', null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(help_text="Member's last name", max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='notes',
            field=models.TextField(blank=True, help_text='General notes about the member', null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Phone number (supports international formats like +233241234567)', max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='member',
            name='photo_url',
            field=models.URLField(blank=True, help_text="URL to member's profile photo", null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='preferred_contact_method',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone Call'), ('sms', 'SMS/Text Message'), ('whatsapp', 'WhatsApp'), ('mail', 'Physical Mail')], default='email', max_length=15),
        ),
        migrations.AlterField(
            model_name='member',
            name='preferred_language',
            field=models.CharField(choices=[('english', 'English'), ('twi', 'Twi'), ('ga', 'Ga'), ('ewe', 'Ewe'), ('dagbani', 'Dagbani'), ('french', 'French'), ('other', 'Other')], default='english', max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='preferred_name',
            field=models.CharField(blank=True, help_text='Name the member prefers to be called', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='registered_by',
            field=models.ForeignKey(blank=True, help_text='Admin user who registered this member', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='member',
            name='registration_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the member was registered'),
        ),
        migrations.AlterField(
            model_name='member',
            name='registration_source',
            field=models.CharField(choices=[('public_form', 'Public Registration Form'), ('admin_portal', 'Admin Portal'), ('bulk_import', 'Bulk Import'), ('referral', 'Member Referral'), ('event_registration', 'Event Registration'), ('migration', 'Data Migration'), ('manual', 'Manual Entry')], default='public_form', max_length=20),
        ),
        migrations.AlterField(
            model_name='membernote',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_member_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='membernote',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Private notes are only visible to senior staff'),
        ),
        migrations.AlterField(
            model_name='membernote',
            name='note',
            field=models.TextField(help_text='Note content'),
        ),
        migrations.AlterField(
            model_name='membertag',
            name='color',
            field=models.CharField(default='#3B82F6', help_text='Hex color code for the tag (e.g., #FF5733)', max_length=7),
        ),
        migrations.AlterField(
            model_name='membertag',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_member_tags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='membertag',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membertagassignment',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_tag_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='membertagassignment',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_assignments', to='members.membertag'),
        ),
        migrations.AddIndex(
            model_name='bulkimporterror',
            index=models.Index(fields=['import_log', 'row_number'], name='members_bul_import__000b52_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['family'], name='members_mem_family__242ad3_idx'),
        ),
    ]
