# Generated by Django 5.2.1 on 2025-09-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_bulkimporterror_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='alternate_phone',
            field=models.CharField(blank=True, help_text='Alternative phone number', null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number (supports international formats like +233241234567)', null=True),
        ),
    ]
